word_list = {
    'abruptly': 'Adverb: Suddenly and without warning. Describes an action or event that occurs unexpectedly, catching people by surprise.',
    'absurd': 'Adjective: Ridiculously silly or unreasonable. Goes beyond the bounds of reason and logic, often in a comical or exaggerated manner.',
    'abyss': 'Noun: A very deep hole or chasm. Metaphorically, refers to a profound or immeasurable space, conveying a sense of emptiness or vastness.',
    'affix': 'Verb: To attach or stick to something. In linguistics, refers to adding a morpheme to a word to modify its meaning, such as prefixes and suffixes.',
    'askew': 'Adjective: Not straight or level; tilted. Describes something that is crooked or out of alignment, creating a sense of imbalance or disorder.',
    'avenue': 'Noun: A wide street or road. Typically features rows of trees or buildings, providing a scenic and grand passage.',
    'awkward': 'Adjective: Clumsy or uncomfortable. Awkward situations or individuals lack smoothness or grace, leading to discomfort or social unease.',
    'axiom': 'Noun: A self-evident and widely accepted truth. A fundamental principle or rule that is universally recognized and considered indisputable.',
    'azure': 'Noun: A bright, blue color. Often associated with the clear sky on a sunny day or the vibrant hue of a precious gemstone.',
    'bagpipes': 'Noun: A musical instrument with pipes. Characterized by a bag and several pipes, producing a distinct and traditional sound.',
    'bandwagon': 'Noun: Joining a popular trend or activity. Hopping on the bandwagon means adopting a fashionable or widely accepted behavior or opinion.',
    'banjo': 'Noun: A stringed musical instrument. Known for its distinctive twangy sound and often associated with folk and bluegrass music.',
    'bayou': 'Noun: A marshy, slow-moving body of water. Common in the southern United States, a bayou is a waterway with sluggish or stagnant flow.',
    'beekeeper': 'Noun: Someone who keeps and cares for bees. Manages beehives, ensuring the health and productivity of the bee colony.',
    'bikini': 'Noun: A two-piece swimwear. A revealing and fashionable swimsuit, consisting of separate top and bottom pieces.',
    'blitz': 'Noun: A sudden and intense attack. Originally a military term, a blitz can also refer to a rapid and overwhelming assault in sports or other contexts.',
    'blizzard': 'Noun: A severe snowstorm with strong winds. Characterized by heavy snowfall and reduced visibility, blizzards can be hazardous weather conditions.',
    'boggle': 'Verb: To overwhelm or astonish. Boggling the mind refers to causing surprise, confusion, or disbelief due to something extraordinary or perplexing.',
    'bookworm': 'Noun: A person who loves reading books. Often used affectionately, a bookworm is someone deeply devoted to reading and acquiring knowledge.',
    'boxcar': 'Noun: A type of railroad car. Enclosed freight cars used for transporting goods by rail.',
    'boxful': 'Noun: As much as a box can hold. Referring to the quantity that fills or occupies the capacity of a box.',
    'buckaroo': 'Noun: A cowboy or ranch worker. Commonly used in the western United States, buckaroo is synonymous with cowboy or cowhand.',
    'buffalo': 'Noun: A large mammal with shaggy fur and curved horns. Native to North America, buffalo are often associated with the American West.',
    'buffoon': 'Noun: A person who acts silly or foolish. Engages in comical or absurd behavior, often for the amusement of others.',
    'buxom': 'Adjective: Having a full and attractive figure. Typically applied to women, buxom describes a pleasingly plump or curvaceous physique.',
    'buzzard': 'Noun: A large bird of prey. Scavenging birds known for their soaring flight and keen eyesight.',
    'buzzing': 'Noun: A continuous humming sound. A noise produced by insects, machinery, or any rapid vibration.',
    'buzzwords': 'Noun: Trendy or popular words or phrases. Often used in discussions, marketing, or media to attract attention or convey a specific message.',
    'caliph': 'Noun: A Muslim civil and religious leader. Historically, a caliph was a political and spiritual successor to the Prophet Muhammad.',
    'cobweb': 'Noun: A spider\'s web. Intricate networks of silk produced by spiders, often found in corners or abandoned spaces.',
    'cockiness': 'Noun: Excessive self-confidence. A brash and overconfident attitude, often perceived as arrogance or conceit.',
    'croquet': 'Noun: A lawn game with mallets and balls. Involves hitting wooden balls through hoops with mallets on a grassy playing area.',
    'crypt': 'Noun: An underground burial chamber. Often used as tombs or repositories for the deceased, especially in churches or cemeteries.',
    'curacao': 'Noun: A blue liqueur. A flavored alcoholic beverage, often used in cocktails, known for its vibrant blue color.',
    'cycle': 'Noun: A repeating sequence of events. In general terms, a cycle is a series of events that occur in a predictable pattern or order.',
    'daiquiri': 'Noun: A cocktail made with rum and lime. A refreshing drink known for its combination of citrus and rum flavors.',
    'dirndl': 'Noun: A traditional German dress. A feminine and traditional Bavarian or Austrian dress, often worn at cultural events.',
    'disavow': 'Verb: To deny any responsibility. Rejecting or disclaiming any association with a statement, action, or belief.',
    'dizzying': 'Adjective: Causing dizziness or vertigo. Inducing a feeling of lightheadedness, instability, or disorientation.',
    'duplex': 'Noun: A house with two separate living units. A residential building with two separate apartments or living spaces.',
    'dwarves': 'Noun: Plural of dwarf. Mythological beings, often depicted as small and stout, with a reputation for skilled craftsmanship.',
    'embezzle': 'Verb: To steal money entrusted to one. Involves misappropriating funds or assets entrusted for personal gain.',
    'equip': 'Verb: To provide with necessary items. Involves providing someone or something with the tools, gear, or resources required.',
    'espionage': 'Noun: The practice of spying. Activities involving gathering, transmitting, or analyzing information in a secretive or covert manner.',
    'euouae': 'Noun: A medieval musical term. A mnemonic used to remember a sequence of tones in medieval liturgical music.',
    'exodus': 'Noun: A mass departure of people. Describes a large-scale migration or departure, often used to depict a group leaving a place en masse.',
    'faking': 'Verb: Pretending or imitating. Involves creating a false appearance or impression, often to deceive or mislead others.',
    'fishhook': 'Noun: A curved implement for catching fish. A device used in fishing, typically made of metal, with a barbed end to catch fish.',
    'fixable': 'Adjective: Capable of being fixed or repaired. Describes something that can be easily corrected or restored to its original condition.',
    'fjord': 'Noun: A narrow sea or lake between cliffs. Long, narrow inlets with steep sides or cliffs, often created by glacial erosion.',
    'flapjack': 'Noun: A flat, round pancake. A type of griddle cake, usually made with batter consisting of flour, eggs, and milk.',
    'flopping': 'Adjective: Moving or falling with a loose motion. Describes something that moves or hangs in a loose and uncontrolled manner.',
    'fluffiness': 'Noun: The quality of being fluffy or soft. Describes the state of being light, airy, and soft to the touch, like fluffy clouds or pillows.',
    'flyby': 'Noun: A quick flight past a point. A rapid and low-altitude flight over a specific area, often done for observation or display.',
    'foxglove': 'Noun: A tall plant with bell-shaped flowers. A flowering plant known for its tubular, spotted flowers and is sometimes poisonous.',
    'frazzled': 'Adjective: Worn out or frayed. Describes something that is tired, stressed, or showing signs of wear and tear.',
    'frizzled': 'Adjective: Crisp or curled at the edges. Refers to something, often hair or food, that is crisply curled or fried at the edges.',
    'fuchsia': 'Noun: A vivid purplish-red color. A bright and bold color, often resembling a deep pink or purplish-red shade.',
    'funny': 'Adjective: Causing laughter or amusement. Something that evokes laughter or amusement, often due to its comical or entertaining nature.',
    'gabby': 'Adjective: Talkative or chatty. Describes someone who talks a lot or is inclined to engage in lengthy conversations.',
    'galaxy': 'Noun: A system of stars, planets, and other celestial objects. Vast systems of stars, gas, and dust bound together by gravity.',
    'galvanize': 'Verb: To shock or excite into action. Involves stimulating or motivating someone or something into taking action.',
    'gazebo': 'Noun: An open-sided, freestanding structure. A freestanding, open-sided structure often found in gardens or parks, providing a pleasant outdoor space.',
    'giaour': 'Noun: A non-Muslim in Islamic countries. An archaic term used to refer to a non-Muslim or infidel in Islamic countries.',
    'gizmo': 'Noun: A gadget or device. An informal term for a small mechanical or electronic device, often with a specific or unknown purpose.',
    'glowworm': 'Noun: A bioluminescent insect larva. Insects whose larvae emit a soft glow, typically to attract prey or mates.',
    'glyph': 'Noun: A symbol or character. A graphic symbol used to represent a character or concept, often in writing or artistic expressions.',
    'gnarly': 'Adjective: Twisted, knotty, or misshapen. Describes something that is rugged, twisted, or has a rough and uneven surface.',
    'gnostic': 'Adjective: Relating to knowledge or understanding. Refers to a set of religious and philosophical beliefs emphasizing spiritual knowledge and enlightenment.',
    'gossip': 'Noun: Casual or idle talk about others. Involves the sharing of rumors, personal information, or details about others, often without their knowledge.',
    'grogginess': 'Noun: The state of being dazed or weak. Describes a feeling of drowsiness, disorientation, or weakness, often experienced upon waking or after an illness.',
    'haiku': 'Noun: A short Japanese poem with three lines. A traditional form of Japanese poetry, consisting of three lines with a specific syllable pattern.',
    'haphazard': 'Adjective: Lacking any obvious order or organization. Describes something done without careful planning or order, often resulting in randomness or chaos.',
    'hyphen': 'Noun: A punctuation mark (-) indicating a break or connection. Used to join words or parts of words, indicating a connection or separation.',
    'iatrogenic': 'Adjective: Induced by medical treatment or intervention. Describes conditions or effects caused unintentionally by medical treatment or intervention.',
    'icebox': 'Noun: A container or room for keeping things cool. A container, often insulated, used for storing ice or keeping perishable items cool.',
    'injury': 'Noun: Harm or damage to the body. Refers to physical harm or damage to the body, often resulting from accidents, falls, or other traumatic events.',
    'ivory': 'Noun: A hard, creamy-white material from animal tusks. A dense and smooth material obtained from the tusks of elephants and other animals.',
    'ivy': 'Noun: A climbing or trailing plant. A woody vine with aerial roots, often used for decorative purposes in gardens or landscapes.',
    'jackpot': 'Noun: A large cash prize or reward. A substantial amount of money or a significant prize, often won in gambling or lotteries.',
    'jaundice': 'Noun: A yellowing of the skin and eyes. A medical condition characterized by yellow discoloration of the skin and eyes, indicating liver problems.',
    'jawbreaker': 'Noun: A hard candy that is difficult to bite. A large, hard candy that requires prolonged and vigorous chewing.',
    'jaywalk': 'Verb: To cross a street without using a crosswalk.',
    'jazziest': 'Adjective: The most stylish or lively in jazz. Describes something that is the most stylish, energetic, or vibrant, especially in the context of jazz music.',
    'jazzy': 'Adjective: Energetic, stylish, or flashy. Refers to something that is lively, stylish, or has the vibrant and improvisational qualities associated with jazz.',
    'jelly': 'Noun: A sweet, fruit preserve. A clear or translucent fruit spread made from fruit juice, sugar, and pectin.',
    'jigsaw': 'Noun: A puzzle with small, irregular pieces. A puzzle consisting of small, irregularly shaped pieces that fit together to form a complete picture.',
    'jinx': 'Noun: A curse or spell bringing bad luck. Refers to a superstition or belief that saying or doing something specific will bring bad luck.',
    'jiujitsu': 'Noun: A Japanese martial art. A Japanese martial art that focuses on ground fighting and self-defense techniques.',
    'jockey': 'Noun: A person who rides horses in races. A skilled rider who competes in horse races, guiding and controlling the horse during the race.',
    'jogging': 'Verb: Running at a slow, steady pace. A form of running at a slower and steadier pace, often for exercise or recreational purposes.',
    'joking': 'Verb: Engaging in humorous speech or action. Involves making humorous remarks or engaging in playful behavior to amuse oneself or others.',
    'jovial': 'Adjective: Cheerful and friendly. Describes someone who is good-natured, cheerful, and full of high spirits.',
    'joyful': 'Adjective: Feeling great happiness or delight. Describes a state of being full of joy, happiness, or intense delight.',
    'juicy': 'Adjective: Full of juice or flavor. Describes something that is moist, succulent, and rich in flavor, often used in the context of food.',
    'jukebox': 'Noun: A coin-operated music-playing device. A machine that plays selected music when a coin is inserted, often found in bars or diners.',
    'jumbo': 'Adjective: Extremely large or massive. Describes something that is exceptionally large, oversized, or massive in size.',
    'kayak': 'Noun: A small, narrow watercraft. A small, narrow watercraft with a covered deck and a double-bladed paddle, often used for water recreation.',
    'kazoo': 'Noun: A simple musical instrument. A simple musical instrument that produces a buzzing sound when the player hums into it.',
    'keyhole': 'Noun: A hole for inserting a key. A small, typically round hole designed for inserting and turning a key to lock or unlock a door or device.',
    'khaki': 'Noun: A light brown color. A light brown or tan color, often associated with military uniforms and casual clothing.',
    'kilobyte': 'Noun: A unit of digital information storage. A unit of digital information storage equal to 1024 bytes or 8,192 bits.',
    'kiosk': 'Noun: A small open-fronted hut or cubicle. A small, open-fronted structure often used for selling newspapers, tickets, or other goods.',
    'kitsch': 'Noun: Art or design considered in poor taste. Refers to art, objects, or design that is considered tacky, sentimental, or in poor taste.',
    'kiwifruit': 'Noun: A fuzzy, brown-skinned fruit. A small, brown-skinned fruit with green flesh and tiny black seeds, known for its tangy flavor.',
    'klutz': 'Noun: A clumsy or awkward person. Someone who is habitually clumsy or awkward in their movements.',
    'knapsack': 'Noun: A small backpack. A small, sturdy backpack often used for carrying personal belongings, especially during outdoor activities.',
    'larynx': 'Noun: The voice box in the throat. The part of the respiratory tract containing the vocal cords, essential for speech production.',
    'lengths': 'Noun: Measurements from end to end. Refers to measurements from one end to the other, often used in the context of size or distance.',
    'lucky': 'Adjective: Having good fortune or luck. Describes someone or something favored by good fortune or chance.',
    'luxury': 'Noun: The state of great comfort and extravagance. Describes a state of living in great comfort and extravagance, often associated with wealth and opulence.',
}
